package com.myspace.bpmshistoriaclinica;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InfoConfirmarPaciente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int idCita;
	private java.lang.Boolean pacienteAsistio;

	private java.lang.String documentoPaciente;

	public InfoConfirmarPaciente() {
	}

	public int getIdCita() {
		return this.idCita;
	}

	public void setIdCita(int idCita) {
		this.idCita = idCita;
	}

	public java.lang.Boolean getPacienteAsistio() {
		return this.pacienteAsistio;
	}

	public void setPacienteAsistio(java.lang.Boolean pacienteAsistio) {
		this.pacienteAsistio = pacienteAsistio;
	}

	public java.lang.String getDocumentoPaciente() {
		return this.documentoPaciente;
	}

	public void setDocumentoPaciente(java.lang.String documentoPaciente) {
		this.documentoPaciente = documentoPaciente;
	}

	public InfoConfirmarPaciente(int idCita, java.lang.Boolean pacienteAsistio,
			java.lang.String documentoPaciente) {
		this.idCita = idCita;
		this.pacienteAsistio = pacienteAsistio;
		this.documentoPaciente = documentoPaciente;
	}

}