package com.myspace.bpmshistoriaclinica;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InfoConfirmaProfesional implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String idCita;
	private java.lang.String nombreProfesional;

	public InfoConfirmaProfesional() {
	}

	public java.lang.String getIdCita() {
		return this.idCita;
	}

	public void setIdCita(java.lang.String idCita) {
		this.idCita = idCita;
	}

	public java.lang.String getNombreProfesional() {
		return this.nombreProfesional;
	}

	public void setNombreProfesional(java.lang.String nombreProfesional) {
		this.nombreProfesional = nombreProfesional;
	}

	public InfoConfirmaProfesional(java.lang.String idCita,
			java.lang.String nombreProfesional) {
		this.idCita = idCita;
		this.nombreProfesional = nombreProfesional;
	}

}