package com.myspace;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InfoPaciente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Documento")
	private java.lang.Integer documento;
	@org.kie.api.definition.type.Label("Nombre completo")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label("Fecha de cita")
	private java.time.LocalDateTime fechaCIta;

	@org.kie.api.definition.type.Label(value = "Sede")
	private java.util.List<java.lang.String> sede;

	public InfoPaciente() {
	}

	public java.lang.Integer getDocumento() {
		return this.documento;
	}

	public void setDocumento(java.lang.Integer documento) {
		this.documento = documento;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.time.LocalDateTime getFechaCIta() {
		return this.fechaCIta;
	}

	public void setFechaCIta(java.time.LocalDateTime fechaCIta) {
		this.fechaCIta = fechaCIta;
	}

	public java.util.List<java.lang.String> getSede() {
		return this.sede;
	}

	public void setSede(java.util.List<java.lang.String> sede) {
		this.sede = sede;
	}

	public InfoPaciente(java.lang.Integer documento, java.lang.String nombre,
			java.time.LocalDateTime fechaCIta,
			java.util.List<java.lang.String> sede) {
		this.documento = documento;
		this.nombre = nombre;
		this.fechaCIta = fechaCIta;
		this.sede = sede;
	}

}